version: 1
policy:
  pullRequests: collaborators
tasks:
  $match:
    '(tasks_for == "github-pull-request" && event["action"] in ["opened","reopened","synchronize"])':
      taskId:
        $eval: as_slugid("pr_task")
      provisionerId: built-in
      workerType: succeed
      deadline: {$fromNow: '1 minute'}
      payload: {}
      metadata:
        name: foo
        description: bar
        owner: '${event.sender.login}@users.noreply.github.com'
        source: '${event.repository.url}'
