version: 1
policy:
  pullRequests: collaborators
tasks:
  $match:
    '(tasks_for == "github-pull-request" && event["action"] in ["opened","reopened","synchronize"])':
      taskId:
        $eval: as_slugid("pr_task")
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      deadline: {$fromNow: '1 day'}
      payload:
        maxRunTime: 3600
        image: node
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            echo HELLO WORLD
      metadata:
        name: foo
        description: bar
        owner: '${event.sender.login}@users.noreply.github.com'
        source: '${event.repository.url}'
